import type { Metadata } from "next";
import "../globals.css";
import { AppProvider } from "@/context/AppContext";
import { UserProvider } from "@/context/UserContext";
import AuthProvider from "@/providers/AuthProvider";
import { ToastContainer } from "react-toastify";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import LanguageSwitcher2 from "@/components/ui/LanguageSwitcher2";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body suppressHydrationWarning={true} className="">
        <UserProvider>
          <AppProvider>
            <AuthProvider>
              <NextIntlClientProvider messages={messages}>
                {children}
                <LanguageSwitcher2 />
              </NextIntlClientProvider>
            </AuthProvider>
            <ToastContainer position="top-right" autoClose={3000} />
          </AppProvider>
        </UserProvider>
      </body>
    </html>
  );
}
